name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: pragmatedev/vitewp-docker
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory /__w/footmate.pro/footmate.pro
      - working-directory: wp-content/themes/footmate
        run: composer install
      - working-directory: wp-content/themes/footmate
        run: yarn install
      - working-directory: wp-content/themes/footmate
        run: yarn lint